project:
  type: website

website:
  announcement:
    icon: info-circle
    dismissable: false
    content: |
      **I’m on the lookout for full-time Data Science (or similar) positions.
      If you have any leads or just want to chat, [feel free to reach
      out](mailto:contact@arumoy.me)! [Here’s my resume](resume.html) if you’re interested in
      checking it out. Thanks a bunch!** 😊
    type: warning
    position: below-navbar
  title: "Arumoy Shome"
  site-url: "https://arumoy.me"
  description: "Arumoy Shome's Website"
  back-to-top-navigation: true
  navbar:
    left:
      - blogs.qmd
      - talks.qmd
      - publications.qmd
      - license.qmd
    right:
      - icon: rss
        href: blogs.xml
      - icon: github
        href: https://github.com/arumoy-shome
      - icon: twitter
        href: https://twitter.com/arumoy_shome
      - icon: linkedin
        href: https://linkedin.com/in/arumoyshome
  page-footer:
    left: "Copyright Arumoy Shome 2018-Present"

    center: "All materials on this website are open sourced under the CC BY 4.0 license."
    right:
      - icon: github
        href: https://github.com/arumoy-shome
      - icon: twitter
        href: https://twitter.com/arumoy_shome
      - icon: linkedin
        href: https://linkedin.com/in/arumoyshome
format:
  html:
    email-obfuscation: javascript
    theme: cosmo
    css: styles.css
bibliography: bibliography.bib
reference-location: margin
citation-location: margin
resources:
  - CNAME
code-annotations: hover
execute:
  freeze: auto
