project:
  type: website
  output-dir: docs

website:
  title: "Arumoy Shome"
  site-url: https://arumoy.me
  description: "Arumoy Shome's Website"
  back-to-top-navigation: true
  navbar:
    left:
      - blogs.qmd
      - talks.qmd
      - projects.qmd
      - publications.qmd
      - license.qmd
    right:
      - icon: github
        href: https://github.com/arumoy-shome
      - icon: twitter
        href: https://twitter.com/arumoy_shome
      - icon: linkedin
        href: https://linkedin.com/in/arumoyshome
  page-footer:
    left: "Copyright 2023, Arumoy Shome"

    center: "All materials on this website are open sourced under the CC BY-NC-SA 3.0 license."
    right:
      - icon: github
        href: https://github.com/arumoy-shome
      - icon: twitter
        href: https://twitter.com/arumoy_shome
      - icon: linkedin
        href: https://linkedin.com/in/arumoyshome
format:
  html:
    theme: cosmo
    css: styles.css
    mainfont: "Iosevka Aile"
    monofont: "Iosevka"
bibliography: bibliography.bib
reference-location: margin
citation-location: margin
resources:
  - CNAME
  - fonts
code-annotations: hover
