site-title: "Arumoy Shome"
site-url: "https://arumoy.me"
description: "Arumoy Shome's Website"
title-suffix: "Arumoy Shome"
author: "Arumoy Shome"
copyright: "Copyright Arumoy Shome 2018-Present"
license: "All materials on this website are open sourced under the CC BY 4.0 license."
nav:
  - href: "/blogs.html"
    text: "blogs"
  - href: "/talks.html"
    text: "talks"
  - href: "/publications.html"
    text: "publications"
  - href: "/resume.html"
    text: "resume"
  - href: "/license.html"
    text: "license"
links:
  - href: "https://github.com/arumoy-shome"
    text: "Github"
  - href: "https://linkedin.com/in/arumoyshome"
    text: "LinkedIn"
  - href: "/blogs.xml"
    text: "RSS"
